version: '3.7'
services:

    ping:
        build: ping

    calc:
        build: calc

    soma:
        build: soma

    sub:
        build: sub
    mult:
        build: mult
        deploy:
            replicas: 3
        ports:
            - "8000"

    nginx:
        image: nginx:latest
        container_name: nginx
        build: nginx
        ports:
            - 8000:80
        depends_on:
           - ping
           - calc
           - soma
           - sub
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf